// Generated by https://quicktype.io

export interface FeaturedCompany {
  id: number;
  title: string;
  address: string;
  features: string[];
  info: string;
  image: string;
}

export const FeaturedCompanies: FeaturedCompany[] = [
  {
    id: 1,
    title: 'Griffon Securities PVT. LTD.',
    address: 'Sari street, Riyadh',
    features: ['Full Time', 'Feature 2'],
    info: 'At dolore magna aliqua ut enim ad minim veniam us nostrud exercitation ulamco aliquip ex ea commodo da consequat duis At dolore magna .',
    image: 'assets/images/images/lighting.jpg',
  },
  {
    id: 2,
    title: 'California Private Securites',
    address: 'Sari street, Riyadh',
    features: ['Full Time', 'Feature 2'],
    info: 'At dolore magna aliqua ut enim ad minim veniam us nostrud exercitation ulamco aliquip ex ea commodo da consequat duis At dolore magna .',
    image: 'assets/images/images/tvit.jpg',
  },
  {
    id: 3,
    title: 'Tactical Securities',
    address: 'Sari street, Riyadh',
    features: ['Full Time', 'Feature 2'],
    info: 'At dolore magna aliqua ut enim ad minim veniam us nostrud exercitation ulamco aliquip ex ea commodo da consequat duis At dolore magna .',
    image: 'assets/images/images/fossa.jpg',
  },
  {
    id: 4,
    title: 'Shield Securities',
    address: 'Haiti, Riyadh',
    features: ['Full Time', 'Feature 2'],
    info: 'At dolore magna aliqua ut enim ad minim veniam us nostrud exercitation ulamco aliquip ex ea commodo da consequat duis At dolore magna .',
    image: 'assets/images/images/tower.jpg',
  },
  {
    id: 5,
    title: 'Eagles Task Forces',
    address: 'Slovak Sari street, Riyadh',
    features: ['Full Time', 'Feature 2'],
    info: 'At dolore magna aliqua ut enim ad minim veniam us nostrud exercitation ulamco aliquip ex ea commodo da consequat duis At dolore magna .',
    image: 'assets/images/images/solaytic.jpg',
  },
];

export const FeaturedCompaniesAr: FeaturedCompany[] = [
  {
    id: 1,
    title: 'غريفون للحماية بيفيتي المحدودة',
    address: 'شارع صاري الرياض',
    features: ['دوام كامل', 'الميزة الثانية'],
    info: 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة',
    image: 'assets/images/images/lighting.jpg',
  },
  {
    id: 2,
    title: 'كاليفورنيا للحماية الخاصة',
    address: 'شارع صاري الرياض',
    features: ['دوام كامل', 'الميزة الثانية'],
    info: 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة',
    image: 'assets/images/images/tvit.jpg',
  },
  {
    id: 3,
    title: 'تكتيكال لخدمات الحماية',
    address: 'شارع صاري الرياض',
    features: ['دوام كامل', 'الميزة الثانية'],
    info: 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة',
    image: 'assets/images/images/fossa.jpg',
  },
  {
    id: 4,
    title: 'شيلد لانظمة الحماية',
    address: 'شارع صاري الرياض',
    features: ['دوام كامل', 'الميزة الثانية'],
    info: 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة',
    image: 'assets/images/images/tower.jpg',
  },
  {
    id: 5,
    title: 'قوة النسر الخاصة',
    address: 'شارع صاري الرياض',
    features: ['دوام كامل', 'الميزة الثانية'],
    info: 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة',
    image: 'assets/images/images/solaytic.jpg',
  },
];
