import { JobDetails } from './job-details.enum';
export interface JobApplication {
  created: string;
  createdDateTime: string;
  sinceTime: string;
  id: number;
  phone: string;
  notes: string;
  jobTypeId: null;
  jobApplicationAttachments: AppAttachment[];
  companyJobId: number;
  securityGuardId: number;
  securityGuard: securityGuard;
  companyJob: JobDetails;
}

export interface securityGuard {
  firstName: string;
  lastName: string;
  email: string;
}

// Generated by https://quicktype.io

export interface AppAttachment {
  id: number;
  attachment: Attachment;
}

export interface Attachment {
  id: number;
  imageId: string;
  name: string;
  fullLink: string;
}
